name: 'Eco Infra Action'
description: 'Report on emissions directly from your CI/CD pipeline'
branding:
  icon: 'terminal'
  color: 'green'
inputs:
  token:
    description: 'API Token, find this on the Eco Infra platform dashboard under user settings'
    required: true

  project-name:
    description: 'Identifier for the project'
    required: true

  plan-file:
    description: 'Path of the plan file to use for the Eco Infra Platform'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
