on: [push]

jobs:
  Test_Eco_infra_Action:
    runs-on: ubuntu-latest
    name: A job to run the Eco Infra Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - run: |
          cd terraform
          terraform init
          terraform plan -out=plan.tfplan
          terraform show -json plan.tfplan > plan.json
          cd ..
      - name: Run Eco Infra Action
        uses: ./
        with:
          token: ${{ secrets.ECO_INFRA_API_TOKEN }}
          project-name: 'my-project'
          plan-file: './terraform/plan.json'
          apply: 'true'
  Release:
    name: Release
    runs-on: ubuntu-latest
    needs: Test_Eco_infra_Action
    strategy:
      matrix:
        node: [ 20 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: |
          npm ci

      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}